package enums;

public enum UserAction {
    EDIT_PERSONAL_INFO,
    SHOW_TRANSACTIONS,
    DISPLAY_PERSONAL_INFO,
    SIGN_IN,
    DISPLAY_EMPLOYEE_INFO,
    AUTH_EMPLOYEE,
    CREATE_EMPLOYEE_ACCOUNT,
    DISPLAY_DETAILS,
    TRANSACTION_PROCESS,
    DISPLAY_BALANCE,
    STATE_CHECK,
    GENERATE_ACCOUNT_NUMBER,
    PROFIT_GAIN,
    CREATE,
    EDIT,
    SEARCH,
    DELETE,
    DEPOSIT,
    WITHDRAWAL,
    DISPLAY_CLIENT_INFO,
    TRANSFER
}
